# Generated by Django 5.2.7 on 2025-11-19 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('azucares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'nutricional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caducidad', models.DateField()),
                ('elaboracion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(blank=True, null=True)),
                ('modificado', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.DateTimeField(blank=True, null=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.categorias')),
                ('nutricional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.nutricional')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=7)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.productos')),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IngresoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('movimientos_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientosinventario')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'db_table': 'ingreso_stock',
                'managed': True,
            },
        ),
    ]
